(define (problem logistic-i)
  (:domain logistic)
  (:objects truck package1 changi tampinese bedok)
  (:init (truck truck)
    (package package1)
    (location changi)
    (location tampinese)
    (location bedok)
    (road tampinese changi)
    (road changi tampinese)
    (road changi bedok)
    (road bedok changi)
    (road tampinese bedok)
    (road bedok tampinese)
    (truckat truck tampinese)
    (packageat package1 bedok))
  (:goal (and (packageat package1 changi))))