(define (problem logistic-ii)
  (:domain logistic)
  (:objects truck package1 package2 changi tampinese bedok)
  (:init (truck truck)
    (package package1)
    (package package2)
    (location changi)
    (location tampinese)
    (location bedok)
    (road tampinese changi)
    (road changi tampinese)
    (road changi bedok)
    (road bedok changi)
    (road tampinese bedok)
    (road bedok tampinese)
    (truckat truck tampinese)
    (packageat package1 bedok)
    (packageat package2 changi))
  (:goal (and (packageat package1 changi) (packageat package2 bedok))))